version: "3.6"
services:
  one:
    image: logging-app:1.0
    environment:
      - LOG_PREFIX=app-one
    ports:
      - 8080:8080

  two:
    image: logging-app:1.0
    environment:
      - LOG_PREFIX=app-two
    ports:
      - 8082:8080
